name: $name
version: $version
main: com.geekazodium.splashdown.SplashDown
description: $description
load: STARTUP
authors:
  - Author
api-version: "$apiVersion"
commands:
    item:
        description: gets custom item
        permission: operator
        usage: /item <id/name>
